### ISSUE TITLE
small plus

### ISSUE THREAD

**Issue by carsten44** [frozeman/feindura-flat-file-cms#13]
Some small functions or adds to optimize feindura...

**Comment by carsten44** [comment]
Display the pagenumber (filenumber example '42.php') in the backend (pagelist) beside the name of the page. The designer get the searching page without a click on the page to refresh the pagelist.

**Comment by frozeman** [comment]
that would grow the panelist names to big, and the also should the page filename not really matter.
what  could implement is that the page id is hidden in the title text so when you type the number of an page id in the filter it will page list filter out the page with this id for you.
What do you think?

**Comment by frozeman** [comment]
the file number is now visible when you hover over the pages names un a tooltip, like this:

ID: 42
