### ISSUE TITLE
Pagination plugin and disabled cookies in the frontend

### ISSUE THREAD

**Issue by victorgavilan** [frozeman/feindura-flat-file-cms#24]
Hello, Fabian, I just develop a pagination plugin for Feindura you could take a look at [https://github.com/victorgavilan/feindura-flat-file-cms](https://github.com/victorgavilan/feindura-flat-file-cms) in the plugins folder.

If you like I can do a pull request to include it in the master feindura repository.

Another thing that I would like you take a look is the cookies branch in my fork repository of feindura. There I have added the posibility for the user to disabled the use of sessions and cookies in the front end. This is useful in some european countries where there is not allowed to install cookies without the autorization of the user that visit our site. 

If you think it is right and want to include this changes into feindura I could do another pull request to the master or development branch.

**Comment by frozeman** [comment]
do you have a website runnig where i can see the pagination plugin at work?

Fabian Vogelsteller

Web Developer

TunedIn Media GmbH
Mulackstr. 19
10119 Berlin
Mobile: +49 1577 156 80 60
E-Mail: 
fabian.vogelsteller@tunedin.de

Homepage: www.tunedin.de

Registergericht: Amtsgericht Charlottenburg, Handelsregister HRB 133483B
Geschäftsführer: Sebastian Bartz, Kaspar Jost Klippgen

This message may contain confidential and/or privileged information. If you are not the addressee or authorized to receive this on behalf of the addressee, you must not use, copy, disclose or take any action based on this message or any information herein. If you have received this message in error, please advise the sender immediately by reply e-mail and delete this message. Thank you for your cooperation.

**Comment by victorgavilan** [comment]
You could see a demo here http://yuilibrary.es/feindura/page/plugins/paginator-plugin/ and login into the back panel with user **admin** and password **admin**.

It needs a little modifications to make it totally multilingual, but you can get and idea about how it works.

**Comment by frozeman** [comment]
looks quite nice!

thanks!

One hint, for Category, i would mention that you have to add the category id (you could probably also list the categories in an select box i guess)

I will definitely add this to the repro and put it up on the page under the download section (on the bottom it shows custom plugins)

Fabian Vogelsteller

Web Developer

TunedIn Media GmbH
Mulackstr. 19
10119 Berlin
Mobile: +49 1577 156 80 60
E-Mail: 
fabian.vogelsteller@tunedin.de

Homepage: www.tunedin.de

Registergericht: Amtsgericht Charlottenburg, Handelsregister HRB 133483B
Geschäftsführer: Sebastian Bartz, Kaspar Jost Klippgen

This message may contain confidential and/or privileged information. If you are not the addressee or authorized to receive this on behalf of the addressee, you must not use, copy, disclose or take any action based on this message or any information herein. If you have received this message in error, please advise the sender immediately by reply e-mail and delete this message. Thank you for your cooperation.

**Comment by victorgavilan** [comment]
Ok, when I have it finished I will give you a link to get the plugin. I will add the category selector, good hint. 
Thanks
