### ISSUE TITLE
Strict Standards: Non-static method StatisticFunctions::getCurrentCategoryId() should not be called statically

### ISSUE THREAD

**Issue by ghost** [frozeman/feindura-flat-file-cms#27]
Hello Developers,
with me is need for assistance and I have installed the latest version of Feindura. 

It was a demo site package. I have renamed only the directory "feinduraDemoSite" in "Feindura". Now I have this error in the frontend.

```
Strict Standards: Non-static method StatisticFunctions::getCurrentCategoryId() should not be called statically, assuming $this from incompatible context in /www/htdocs/xxxxxxxx/feindura/cms/library/classes/FeinduraBase.class.php on line 325

Strict Standards: Non-static method GeneralFunctions::replaceLinks() should not be called statically, assuming $this from incompatible context in /www/htdocs/xxxxxxxxx/feindura/cms/library/classes/FeinduraBase.class.php on line 1150

Strict Standards: Non-static method GeneralFunctions::replaceSnippets() should not be called statically, assuming $this from incompatible context in /www/htdocs/xxxxxxx/feindura/cms/library/classes/FeinduraBase.class.php on line 1151
```

Who can help. Unfortunately I'm unable to continue.

Thank you in advance.

**Comment by frozeman** [comment]
You set the "strict standard" for you PHP installation. Please look in your PHP config on how to change that.

Be aware that i'm not actively developing feindura anymore, as i'm very busy with other projects.
