### ISSUE TITLE
chapta -> captcha

### ISSUE THREAD

**Issue by danrl** [frozeman/feindura-flat-file-cms#4]
I just saw a typo while browsing the source of a HTML file.

Plugin ContactForm generates class="chapta_..." but I think you meant Captcha?

"Completely Automated Public Turing test to tell Computers and Humans Apart"

**Comment by frozeman** [comment]
yeah, i was sitting in a course and they also named it captcha... i was confused, i took the chapta script from another website and it was named like this, i never checked if its correct.

i will change this.
