### ISSUE TITLE
Disable Captcha on ContactForm

### ISSUE THREAD

**Issue by danrl** [frozeman/feindura-flat-file-cms#5]
I'd like to see a option to disable the captcha in a contact form. It fails do appear where I installed it, and I don't need it. All others field are pretty easy to enable or disable in the settings. A option for the captcha would be great!

**Comment by frozeman** [comment]
its true, yeah i think i will add this.

**Comment by frozeman** [comment]
add in the latest commit, but if you want to update you have to run the update.php first

**Comment by danrl** [comment]
Thanks a lot, it worked!

**Comment by frozeman** [comment]
no prob..
