### ISSUE TITLE
add multi language pages

### ISSUE THREAD

**Issue by frozeman** [frozeman/feindura-flat-file-cms#6]
each page created in feindura should have the option to be multi language, means adding different languages for the content, description and title.

**Comment by Mutz** [comment]
I'd love to have that Feature. Maintaining a multilanguage Site would be a Dream

**Comment by frozeman** [comment]
good to hear,

how you think it should be implemented?

i thought about either each page can have a button which says "add language" and you add  a new language there, that also means that some pages can have multiple languages others not. this helps, when you don't have another language content for a page, it would always show the language available.

or you have to setup an list of languages in the settings and all pages have like a tab where you can write the title content etc in different languages. this also means that every page will have to have the same multiple languages, and if not filled, would be shown as empty in the frontend.

do you any ideas?

fabian

**Comment by Mutz** [comment]
I'd like your first proposal, exactly for the mentioned Reason. Also it would be much easier to fill a Site with content and it displays where there is allready Content in another Language.

As the Site where i'm using Feindura (Website of my Grandfather) currently is maintained only by me and I have not that much Time to update all Content at once I could publish what i have and than go on adding more Content as i have time.

Martin
