### ISSUE TITLE
Add Template support

### ISSUE THREAD

**Issue by Mutz** [frozeman/feindura-flat-file-cms#8]
Add the abbility to eg. create a site Stub (maybe within a Category) and than be able to use that in a Page as a Template.

An example :

I have a Page with a Discography. Everytime a new Album is released the Author has to update the Site.

I create a new Site in Category 'Layout Elements' with the Template for a Album entry.
If the Author has to add a new Album he then can select the Template in the editor and change all needed Content.

Any recommendation how to implement that Feature?

**Comment by frozeman** [comment]
i think i did this already in the new 1.1.6 version.
if you create a new page, you can select any page as template, so you only have to change the content and save..

is that what you mean?

**Comment by Mutz** [comment]
Sorry for getting back lattely, but real life got me....

I saw your implementation. But that works only with a new Page.
I mean to be able to insert a template like a snippet in a existing Page

**Comment by frozeman** [comment]
hm, it would be strange, to change the content of an existing page completely.

what you could do is got to the page you want to copy, goto the source code and then mark all and copy and paste in the new page's source code.

**Comment by Mutz** [comment]
Thats right, but i want my grandfather to do it by himself ;)

I don't want to chnage the complete content, i want to add a entry forthe CD by the Template. So you only have to chnage the Title and Description... Maybe he can copy it... we'll see

**Comment by frozeman** [comment]
but for this the current template system should work..?
you create a new page in , say category "albums" and then you choose an old page of a cd as template.
